### ISSUE TITLE
Add better logging

### ISSUE THREAD

**Issue by 12932** [thomasasfk/plex-auto-delete#6]
Currently the only "logging" is printing to stdout, it would be nice to have a log file that just lives alongside the script that shows timestamps and stuff

**Comment by 12932** [comment]
https://github.com/thomasasfk/plex-auto-delete/pull/8

**Comment by thomasasfk** [comment]
https://github.com/thomasasfk/plex-auto-delete/pull/8 & https://github.com/thomasasfk/plex-auto-delete/pull/9
